name: Deploy to Firebase Hosting ğŸ”¥

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code âœ…ï¸
        uses: actions/checkout@v4

      - name: Install and Build ğŸ—ï¸
        run: |
          npm ci && npm run build

      - name: Deploy to Staging ğŸ”§
        if: ${{ github.ref_name == 'develop' }}
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_COOKBOT_JP }}
          channelId: staging
          projectId: cookbot-jp

      - name: Deploy to Production ğŸš€
        if: ${{ github.ref_name == 'master' }}
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_COOKBOT_JP }}
          channelId: live
          projectId: cookbot-jp
